//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test20._2._22
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CourseID { get; set; }
        public Nullable<int> CourseCode { get; set; }
        public string CourseName { get; set; }
        public Nullable<decimal> CreditPoints { get; set; }
        public Nullable<int> PassGrade { get; set; }
    }
}
