//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test20._2._22
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string FullName { get; set; }
        public string IdNum { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime RegisterDate { get; set; }
    }
}
